[package]
name = "genealogy"
version = "0.1.0"
authors = ["chris <chris@tux.io>"]

[dependencies]
rocket = "0.3.0"
rocket_codegen = "0.3.0"
diesel = { version = "0.15.0", features = ["postgres"] }
diesel_codegen = { version = "0.15.0", features = ["postgres"] }
dotenv = "0.9.0"